name: tvemoves
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ampl-mp=3.1.0
  - aom=3.9.1
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - cairo=1.18.0
  - dav1d=1.2.1
  - expat=2.6.2
  - ffmpeg=7.0.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - harfbuzz=8.5.0
  - icu=73.2
  - ipopt=3.14.16
  - lame=3.100
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdrm=2.4.121
  - libedit=3.1.20191231
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgomp=13.2.0
  - libhwloc=2.10.0
  - libiconv=1.17
  - libidn2=2.3.7
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libopenvino=2024.2.0
  - libopenvino-auto-batch-plugin=2024.2.0
  - libopenvino-auto-plugin=2024.2.0
  - libopenvino-hetero-plugin=2024.2.0
  - libopenvino-intel-cpu-plugin=2024.2.0
  - libopenvino-intel-gpu-plugin=2024.2.0
  - libopenvino-intel-npu-plugin=2024.2.0
  - libopenvino-ir-frontend=2024.2.0
  - libopenvino-onnx-frontend=2024.2.0
  - libopenvino-paddle-frontend=2024.2.0
  - libopenvino-pytorch-frontend=2024.2.0
  - libopenvino-tensorflow-frontend=2024.2.0
  - libopenvino-tensorflow-lite-frontend=2024.2.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libscotch=7.0.4
  - libspral=2024.05.08
  - libsqlite=3.46.0
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.14.1
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - metis=5.1.0
  - mumps-include=5.7.2
  - mumps-seq=5.7.2
  - ncurses=6.5
  - nettle=3.9.1
  - ocl-icd=2.3.2
  - openh264=2.4.1
  - openssl=3.3.1
  - p11-kit=0.24.1
  - pcre2=10.44
  - pixman=0.43.2
  - pthread-stubs=0.4
  - pugixml=1.14
  - python=3.12.4
  - readline=8.2
  - setuptools=70.1.1
  - snappy=1.2.0
  - svt-av1=2.1.0
  - tbb=2021.12.0
  - tk=8.6.13
  - tzdata=2024a
  - unixodbc=2.3.12
  - wayland=1.23.0
  - wayland-protocols=1.36
  - wheel=0.43.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.3.1
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - asttokens==2.4.1
      - attrs==23.2.0
      - black==23.12.0
      - build==1.0.3
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.2
      - decorator==5.1.1
      - executing==2.0.1
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - idna==3.7
      - iniconfig==2.0.0
      - ipykernel==6.29.4
      - ipython==8.25.0
      - jedi==0.19.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multidict==6.0.5
      - mypy==1.6.1
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - numpy==1.26.1
      - packaging==24.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==10.3.0
      - pip==24.1.1
      - platformdirs==4.2.2
      - pluggy==1.5.0
      - ply==3.11
      - prompt-toolkit==3.0.47
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.18.0
      - pyomo==6.6.2
      - pyparsing==3.1.2
      - pyproject-hooks==1.1.0
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pytest==7.4.3
      - python-dateutil==2.9.0.post0
      - pytweening==1.0.3
      - pyzmq==26.0.3
      - six==1.16.0
      - stack-data==0.6.3
      - sympy==1.12
      - tornado==6.4.1
      - tqdm==4.66.1
      - traitlets==5.14.3
      - tween==0.0.3
      - types-tqdm==4.66.0.0
      - typing-extensions==4.12.2
      - wcwidth==0.2.13
      - yarl==1.9.4
